name: Lint

on:
  push:
  pull_request:
  workflow_run:
    workflows: ["Publish"]
    types:
      - completed
  workflow_dispatch:
    inputs:
      ref:
        description: 'Branch or tag to lint'
        required: false
        default: ''
        type: string

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.ref || github.ref }}

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install pip dependencies
        run: |
          pip3 install semver luadata

      - name: Install apt dependencies
        run: |
          sudo rm -f /var/lib/man-db/auto-update
          sudo apt install --no-install-recommends lua5.1 p7zip-full

      - name: Write secret to file
        run: |
          cat > secret.jx3dat << 'EOF'
          ${{ secrets.SECRET_JX3DAT }}
          EOF

      - name: Run CI Command
        run: |
          python3 \!src-dist/ci.py
